/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface':                  '#f8f9ff',
        'surface-dim':              '#cbdbf5',
        'surface-bright':           '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#eff4ff',
        'surface-container':        '#e5eeff',
        'surface-container-high':   '#dce9ff',
        'surface-container-highest':'#d3e4fe',
        'on-surface':               '#0b1c30',
        'on-surface-variant':       '#434654',
        'inverse-surface':          '#213145',
        'inverse-on-surface':       '#eaf1ff',
        'outline':                  '#737685',
        'outline-variant':          '#c3c6d6',
        'surface-tint':             '#0c56d0',
        'primary':                  '#003d9b',
        'on-primary':               '#ffffff',
        'primary-container':        '#0052cc',
        'on-primary-container':     '#c4d2ff',
        'inverse-primary':          '#b2c5ff',
        'primary-fixed':            '#dae2ff',
        'primary-fixed-dim':        '#b2c5ff',
        'on-primary-fixed':         '#001848',
        'on-primary-fixed-variant': '#0040a2',
        'secondary':                '#565e74',
        'on-secondary':             '#ffffff',
        'secondary-container':      '#dae2fd',
        'on-secondary-container':   '#5c647a',
        'tertiary':                 '#603b00',
        'on-tertiary':              '#ffffff',
        'tertiary-container':       '#805000',
        'on-tertiary-container':    '#ffc988',
        'tertiary-fixed':           '#ffddb8',
        'tertiary-fixed-dim':       '#ffb95f',
        'on-tertiary-fixed':        '#2a1700',
        'on-tertiary-fixed-variant':'#653e00',
        'error':                    '#ba1a1a',
        'on-error':                 '#ffffff',
        'error-container':          '#ffdad6',
        'on-error-container':       '#93000a',
        'background':               '#f8f9ff',
        'on-background':            '#0b1c30',
        'surface-variant':          '#d3e4fe',
        'surface-tint':             '#0c56d0',
      },
      fontFamily: {
        sans:      ['Inter', 'system-ui', 'sans-serif'],
        mono:      ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-lg':  ['36px', { lineHeight: '44px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600', letterSpacing: '-0.01em' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg':     ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md':     ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm':     ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-md':    ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.05em' }],
        'label-sm':    ['11px', { lineHeight: '14px', fontWeight: '500' }],
        'data-mono':   ['13px', { lineHeight: '20px', fontWeight: '450' }],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm:      '0.125rem',
        md:      '0.25rem',
        lg:      '0.375rem',
        xl:      '0.5rem',
        '2xl':   '0.75rem',
        full:    '9999px',
      },
      spacing: {
        xs:  '4px',
        sm:  '8px',
        md:  '16px',
        lg:  '24px',
        xl:  '32px',
      },
      boxShadow: {
        card:   '0px 4px 6px -1px rgba(0,0,0,0.05)',
        modal:  '0px 10px 15px -3px rgba(0,0,0,0.10)',
        nav:    '0 2px 8px 0 rgba(0,0,0,0.15)',
      },
      width: {
        sidebar: '260px',
      },
    },
  },
  plugins: [],
};
